### ISSUE TITLE
Highlighted version showing summarized

### ISSUE THREAD

**Issue by gksoriginals** [PeoplePlusAI/sunva-frontend#13]
When a text is highlighted instead of summarised it is still showing as summarised instead of highlighted. The type of the processed text is given in the backend response.

**Comment by fbn776** [comment]
Will change this.

**Comment by fbn776** [comment]
Fixed this in https://github.com/PeoplePlusAI/sunva-frontend/commit/97a7f2abf17f6ba0aa5eb71466d683f19c255a81
