### ISSUE TITLE
Duplicate text display in Original STT transcription

### ISSUE THREAD

**Issue by maximaminima** [PeoplePlusAI/sunva-frontend#3]
![image](https://github.com/user-attachments/assets/5cbba788-549a-495b-8bff-04f51b60ac87)

As you can see in FE, there is duplicate text being shown often. Debug and identify the rootcause for this.

**Comment by fbn776** [comment]
I'll check it out

**Comment by fbn776** [comment]
I tested it. Its a frontend issue. It's caused by something being off [here](https://github.com/PeoplePlusAI/sunva-frontend/blob/3c09e33137e0d03b8b43f272e22e0b54ef960a6b/src/app/home/useSunvaAI.ts#L117)

**Comment by gksoriginals** [comment]
@fbn776 I checked the frontend code and tried some logging. The json data is received only once but still the `data.text` is being printed in the log multiple times. Is this due to some web socket or event handler being called multiple times ?
